apiVersion: v1
kind: ConfigMap

metadata:
  name: employee-api-config

data:
  ENVIRONMENT: "{{ .Values.config.environment }}"
  PLATFORM_TEAM: "{{ .Values.config.platformTeam }}"
  VERSION: "{{ .Values.config.version }}"
