apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-api-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: employee-api

  template:
    metadata:
      labels:
        app: employee-api

    spec:
      containers:
      - name: employee-api-container

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: employee-api-config

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 20
